"""create orders and order items

Revision ID: 39709afbd4d4
Revises: c3ce307c4913
Create Date: 2026-08-16 14:01:22.075198

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '39709afbd4d4'
down_revision: Union[str, Sequence[str], None] = 'c3ce307c4913'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('restaurant_id', sa.Integer(), nullable=False),
    sa.Column('table_id', sa.Integer(), nullable=True),
    sa.Column('order_type', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('customer_name', sa.String(length=255), nullable=True),
    sa.Column('customer_phone', sa.String(length=50), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('subtotal', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('tax', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('total', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['table_id'], ['restaurant_tables.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_orders_id'), 'orders', ['id'], unique=False)
    op.create_index(op.f('ix_orders_restaurant_id'), 'orders', ['restaurant_id'], unique=False)
    op.create_index(op.f('ix_orders_status'), 'orders', ['status'], unique=False)
    op.create_index(op.f('ix_orders_table_id'), 'orders', ['table_id'], unique=False)
    op.create_table('order_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('menu_item_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('total', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['menu_item_id'], ['menu_items.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_order_items_id'), 'order_items', ['id'], unique=False)
    op.create_index(op.f('ix_order_items_menu_item_id'), 'order_items', ['menu_item_id'], unique=False)
    op.create_index(op.f('ix_order_items_order_id'), 'order_items', ['order_id'], unique=False)
    op.create_unique_constraint('uq_restaurant_table_number', 'restaurant_tables', ['restaurant_id', 'table_number'])
    op.drop_index(op.f('ix_restaurants_slug'), table_name='restaurants')
    op.drop_column('restaurants', 'timezone')
    op.drop_column('restaurants', 'province')
    op.drop_column('restaurants', 'phone')
    op.drop_column('restaurants', 'secondary_color')
    op.drop_column('restaurants', 'primary_color')
    op.drop_column('restaurants', 'city')
    op.drop_column('restaurants', 'currency')
    op.drop_column('restaurants', 'logo_url')
    op.drop_column('restaurants', 'slug')
    op.drop_column('restaurants', 'is_active')
    op.drop_column('restaurants', 'country')
    op.drop_column('restaurants', 'postal_code')
    op.drop_column('restaurants', 'description')
    op.drop_column('restaurants', 'address')
    op.drop_column('restaurants', 'email')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('restaurants', sa.Column('email', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('restaurants', sa.Column('address', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('restaurants', sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('restaurants', sa.Column('postal_code', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.add_column('restaurants', sa.Column('country', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.add_column('restaurants', sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('restaurants', sa.Column('slug', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.add_column('restaurants', sa.Column('logo_url', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.add_column('restaurants', sa.Column('currency', sa.VARCHAR(length=10), autoincrement=False, nullable=False))
    op.add_column('restaurants', sa.Column('city', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('restaurants', sa.Column('primary_color', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.add_column('restaurants', sa.Column('secondary_color', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.add_column('restaurants', sa.Column('phone', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('restaurants', sa.Column('province', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('restaurants', sa.Column('timezone', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.create_index(op.f('ix_restaurants_slug'), 'restaurants', ['slug'], unique=True)
    op.drop_constraint('uq_restaurant_table_number', 'restaurant_tables', type_='unique')
    op.drop_index(op.f('ix_order_items_order_id'), table_name='order_items')
    op.drop_index(op.f('ix_order_items_menu_item_id'), table_name='order_items')
    op.drop_index(op.f('ix_order_items_id'), table_name='order_items')
    op.drop_table('order_items')
    op.drop_index(op.f('ix_orders_table_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_status'), table_name='orders')
    op.drop_index(op.f('ix_orders_restaurant_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_id'), table_name='orders')
    op.drop_table('orders')
    # ### end Alembic commands ###
