"""prevent duplicate categories per restaurant

Revision ID: 7c8a071f0bd6
Revises: 7ecf11c6bb27
Create Date: 2026-08-16 10:13:59.084531

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7c8a071f0bd6'
down_revision: Union[str, Sequence[str], None] = '7ecf11c6bb27'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_category_restaurant_name', 'categories', ['restaurant_id', 'name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_category_restaurant_name', 'categories', type_='unique')
    # ### end Alembic commands ###
