"""add restaurant id to users

Revision ID: b6dd3eb2766b
Revises: d2b10f5d9d9c
Create Date: 2026-08-15 15:29:52.596740

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b6dd3eb2766b'
down_revision: Union[str, Sequence[str], None] = 'd2b10f5d9d9c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('restaurant_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_users_restaurant_id'), 'users', ['restaurant_id'], unique=False)
    op.create_foreign_key(None, 'users', 'restaurants', ['restaurant_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_index(op.f('ix_users_restaurant_id'), table_name='users')
    op.drop_column('users', 'restaurant_id')
    # ### end Alembic commands ###
